on: push
jobs: 
  build-node:
    runs-on: ubuntu-latest
    container: node:21.7.2
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: node index.js