name: Node.js CI

on: 
  push:
    branches: 
      - main

jobs: 
  build-node:
    runs-on: self-hosted
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.2'
          
      - name: Check Node.js version
        run: node --version
        
      - name: Check npm version
        run: npm --version
        
      - name: Install dependencies
        run: npm install

      - name: Run application
        run: |
          Start-Process -NoNewWindow -FilePath "node" -ArgumentList "../index.js"
